--
-- AUTOGENERATED SCRIPT - PLEASE CHECK BEFORE APPLYING!
--

--
-- Drop old tables if they exist
--

DROP TABLE IF EXISTS pa_application_version;
DROP TABLE IF EXISTS pa_master_keypair;
DROP TABLE IF EXISTS pa_signature_audit;
DROP TABLE IF EXISTS pa_activation;
DROP TABLE IF EXISTS pa_application;
