--------------------------------------------------------
-- Create tables for activation records
--------------------------------------------------------
CREATE TABLE "POWERAUTH"."PA_ACTIVATION"
  (
    "ACTIVATION_ID"               VARCHAR2(37 CHAR),
    "ACTIVATION_ID_SHORT"         VARCHAR2(255 CHAR),
    "ACTIVATION_NAME"             VARCHAR2(255 CHAR),
    "ACTIVATION_OTP"              VARCHAR2(255 CHAR),
    "ACTIVATION_STATUS"           NUMBER(10,0),
    "COUNTER"                     NUMBER(19,0),
    "DEVICE_PUBLIC_KEY_BASE64"    VARCHAR2(255 CHAR),
    "EXTRAS"                      VARCHAR2(1024 CHAR),
    "FAILED_ATTEMPTS"             NUMBER(19,0),
    "MAX_FAILED_ATTEMPTS"         NUMBER(19,0),
    "SERVER_PRIVATE_KEY_BASE64"   VARCHAR2(255 CHAR),
    "SERVER_PUBLIC_KEY_BASE64"    VARCHAR2(255 CHAR),
    "TIMESTAMP_ACTIVATION_EXPIRE" TIMESTAMP (6),
    "TIMESTAMP_CREATED"           TIMESTAMP (6),
    "TIMESTAMP_LAST_USED"         TIMESTAMP (6),
    "USER_ID"                     VARCHAR2(255 CHAR),
    "APPLICATION_ID"              NUMBER(19,0),
    "MASTER_KEYPAIR_ID"           NUMBER(19,0)
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "SYSTEM";
  
--------------------------------------------------------
-- Create tables for applications and application versions
--------------------------------------------------------
CREATE TABLE "POWERAUTH"."PA_APPLICATION"
  (
    "ID"   NUMBER(19,0),
    "NAME" VARCHAR2(255 CHAR)
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "SYSTEM";

CREATE TABLE "POWERAUTH"."PA_APPLICATION_VERSION"
  (
    "ID"                 NUMBER(19,0),
    "APPLICATION_KEY"    VARCHAR2(255 CHAR),
    "APPLICATION_SECRET" VARCHAR2(255 CHAR),
    "NAME"               VARCHAR2(255 CHAR),
    "SUPPORTED"          NUMBER(1,0),
    "APPLICATION_ID"     NUMBER(19,0)
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "SYSTEM" ;

--------------------------------------------------------
-- Create table for master keypairs
--------------------------------------------------------
CREATE TABLE "POWERAUTH"."PA_MASTER_KEYPAIR"
  (
    "ID"                        NUMBER(19,0),
    "MASTER_KEY_PRIVATE_BASE64" VARCHAR2(255 CHAR),
    "MASTER_KEY_PUBLIC_BASE64"  VARCHAR2(255 CHAR),
    "NAME"                      VARCHAR2(255 CHAR),
    "TIMESTAMP_CREATED"         TIMESTAMP (6),
    "APPLICATION_ID"            NUMBER(19,0)
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "SYSTEM" ;

--------------------------------------------------------
-- Create table for signature audit log
--------------------------------------------------------
CREATE TABLE "POWERAUTH"."PA_SIGNATURE_AUDIT"
  (
    "ID"                 NUMBER(19,0),
    "ACTIVATION_COUNTER" NUMBER(19,0),
    "ACTIVATION_STATUS"  NUMBER(10,0),
    "DATA_BASE64"        CLOB,
    "NOTE"               VARCHAR2(255 CHAR),
    "SIGNATURE"          VARCHAR2(255 CHAR),
    "SIGNATURE_TYPE"     VARCHAR2(255 CHAR),
    "TIMESTAMP_CREATED"  TIMESTAMP (6),
    "VALID"              NUMBER(1,0),
    "ACTIVATION_ID"      VARCHAR2(37 CHAR)
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "SYSTEM";
  
REM INSERTING into POWERAUTH.PA_ACTIVATION
SET DEFINE OFF;
REM INSERTING into POWERAUTH.PA_APPLICATION
SET DEFINE OFF;
REM INSERTING into POWERAUTH.PA_APPLICATION_VERSION
SET DEFINE OFF;
REM INSERTING into POWERAUTH.PA_MASTER_KEYPAIR
SET DEFINE OFF;
REM INSERTING into POWERAUTH.PA_SIGNATURE_AUDIT
SET DEFINE OFF;

CREATE UNIQUE INDEX "POWERAUTH"."INDEX_ACTIVATION" ON "POWERAUTH"."PA_ACTIVATION"
  (
    "ACTIVATION_ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "SYSTEM";
CREATE UNIQUE INDEX "POWERAUTH"."INDEX_APPLICATION_ID" ON "POWERAUTH"."PA_APPLICATION"
  (
    "ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "SYSTEM";
CREATE UNIQUE INDEX "POWERAUTH"."INDEX_APPLICATION_VERSION_ID" ON "POWERAUTH"."PA_APPLICATION_VERSION"
  (
    "ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "SYSTEM" ;
CREATE UNIQUE INDEX "POWERAUTH"."INDEX_MASTER_KEYPAIR_ID" ON "POWERAUTH"."PA_MASTER_KEYPAIR"
  (
    "ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "SYSTEM";
CREATE UNIQUE INDEX "POWERAUTH"."INDEX_SIGNATURE_AUDIT_ID" ON "POWERAUTH"."PA_SIGNATURE_AUDIT"
  (
    "ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "SYSTEM" ;
  
  ALTER TABLE "POWERAUTH"."PA_ACTIVATION" ADD PRIMARY KEY ("ACTIVATION_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "SYSTEM" ENABLE;
  ALTER TABLE "POWERAUTH"."PA_ACTIVATION" MODIFY ("MASTER_KEYPAIR_ID" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_ACTIVATION" MODIFY ("APPLICATION_ID" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_ACTIVATION" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_ACTIVATION" MODIFY ("TIMESTAMP_LAST_USED" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_ACTIVATION" MODIFY ("TIMESTAMP_CREATED" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_ACTIVATION" MODIFY ("TIMESTAMP_ACTIVATION_EXPIRE" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_ACTIVATION" MODIFY ("SERVER_PUBLIC_KEY_BASE64" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_ACTIVATION" MODIFY ("SERVER_PRIVATE_KEY_BASE64" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_ACTIVATION" MODIFY ("MAX_FAILED_ATTEMPTS" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_ACTIVATION" MODIFY ("FAILED_ATTEMPTS" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_ACTIVATION" MODIFY ("COUNTER" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_ACTIVATION" MODIFY ("ACTIVATION_STATUS" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_ACTIVATION" MODIFY ("ACTIVATION_OTP" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_ACTIVATION" MODIFY ("ACTIVATION_ID_SHORT" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_ACTIVATION" MODIFY ("ACTIVATION_ID" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_APPLICATION" ADD PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "SYSTEM" ENABLE;
  ALTER TABLE "POWERAUTH"."PA_APPLICATION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_APPLICATION_VERSION" ADD PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "SYSTEM" ENABLE;
  ALTER TABLE "POWERAUTH"."PA_APPLICATION_VERSION" MODIFY ("APPLICATION_ID" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_APPLICATION_VERSION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_MASTER_KEYPAIR" ADD PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "SYSTEM" ENABLE;
  ALTER TABLE "POWERAUTH"."PA_MASTER_KEYPAIR" MODIFY ("APPLICATION_ID" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_MASTER_KEYPAIR" MODIFY ("TIMESTAMP_CREATED" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_MASTER_KEYPAIR" MODIFY ("MASTER_KEY_PUBLIC_BASE64" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_MASTER_KEYPAIR" MODIFY ("MASTER_KEY_PRIVATE_BASE64" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_MASTER_KEYPAIR" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_SIGNATURE_AUDIT" ADD PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "SYSTEM" ENABLE;
  ALTER TABLE "POWERAUTH"."PA_SIGNATURE_AUDIT" MODIFY ("VALID" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_SIGNATURE_AUDIT" MODIFY ("TIMESTAMP_CREATED" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_SIGNATURE_AUDIT" MODIFY ("SIGNATURE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_SIGNATURE_AUDIT" MODIFY ("SIGNATURE" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_SIGNATURE_AUDIT" MODIFY ("ACTIVATION_COUNTER" NOT NULL ENABLE);
  ALTER TABLE "POWERAUTH"."PA_SIGNATURE_AUDIT" MODIFY ("ID" NOT NULL ENABLE);

  ALTER TABLE "POWERAUTH"."PA_ACTIVATION" ADD CONSTRAINT "FK_ACT_MK" FOREIGN KEY ("MASTER_KEYPAIR_ID") REFERENCES "POWERAUTH"."PA_MASTER_KEYPAIR" ("ID") ENABLE;
  ALTER TABLE "POWERAUTH"."PA_ACTIVATION" ADD CONSTRAINT "FK_ACT_APP" FOREIGN KEY ("APPLICATION_ID") REFERENCES "POWERAUTH"."PA_APPLICATION" ("ID") ENABLE;
  ALTER TABLE "POWERAUTH"."PA_APPLICATION_VERSION" ADD CONSTRAINT "FK_APPVER_APP" FOREIGN KEY ("APPLICATION_ID") REFERENCES "POWERAUTH"."PA_APPLICATION" ("ID") ENABLE;
  ALTER TABLE "POWERAUTH"."PA_MASTER_KEYPAIR" ADD CONSTRAINT "FK_MK_APP" FOREIGN KEY ("APPLICATION_ID") REFERENCES "POWERAUTH"."PA_APPLICATION" ("ID") ENABLE;
  ALTER TABLE "POWERAUTH"."PA_SIGNATURE_AUDIT" ADD CONSTRAINT "FK_SIGNAUD_ACT" FOREIGN KEY ("ACTIVATION_ID") REFERENCES "POWERAUTH"."PA_ACTIVATION" ("ACTIVATION_ID") ENABLE;
