--
-- Drop old tables if they exist
--

DROP TABLE "POWERAUTH"."PA_ACTIVATION" CASCADE CONSTRAINTS;
DROP TABLE "POWERAUTH"."PA_APPLICATION" CASCADE CONSTRAINTS;
DROP TABLE "POWERAUTH"."PA_APPLICATION_VERSION" CASCADE CONSTRAINTS;
DROP TABLE "POWERAUTH"."PA_MASTER_KEYPAIR" CASCADE CONSTRAINTS;
DROP TABLE "POWERAUTH"."PA_SIGNATURE_AUDIT" CASCADE CONSTRAINTS;