name: Run Coverity scan and upload results

on:
  workflow_dispatch:
  push:
    branches:
      - 'issues/coverity_scan'

jobs:
  build:
    name: Coverity Scan
    runs-on: ubuntu-latest
    container: ghcr.io/wultra/coverity:latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - run: cov-build --dir cov-int mvn -DskipTests=true compile
      - run: tar czvf powerauth-crypto.tgz cov-int
      - run: mkdir result && cp powerauth-crypto.tgz result
      - uses: actions/upload-artifact@v3
        with:
          name: Analysis
          path: result
      - name: Upload to Coverity Scan Dashboard
        run: |
          curl --form token=${{secrets.COVERITY_SCAN_TOKEN}} \
            --form email=hello@wultra.com \
            --form file=@powerauth-crypto.tgz \
            --form version="${{ github.sha }}" \
            --form description="RC" \
            https://scan.coverity.com/builds?project=wultra%2Fpowerauth-crypto

