name: Java CI with Maven

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - run: |
        mkdir staging
        cp powerauth-java-crypto/target/*.jar powerauth-java-crypto
        cp powerauth-java-http/target/*.jar powerauth-java-http
    - name: Publish PowerAuth Java Crypto
      uses: actions/upload-artifact@v3
      with:
        name: PowerAuth Java Crypto
        path: powerauth-java-crypto
    - name: Publish PowerAuth Java HTTP Utilities
      uses: actions/upload-artifact@v3
      with:
        name: PowerAuth Java HTTP Utilities
        path: powerauth-java-http

