name: Deploy with Maven

on:
  workflow_dispatch:
    branches:
      - 'develop'
      - 'master'
      - 'release/*'
      - 'test/ci'
    inputs:
      style:
        type: choice
        description:
        default: snapshot
        options:
          - snapshot
          - release
  push:
    branches:
     - 'develop'
     - 'test/ci'

    environment:
      type: environment
      default: internal-publish
      description: internal or external repository

jobs:
  maven-deploy:
    name: Deploy to ${{ inputs.environment }}
    uses: wultra/wultra-infrastructure/.github/workflows/maven-deploy.yml@test/ci
    with:
      environment: ${{ inputs.environment }}
      style: ${{ inputs.style }}
    secrets:
      username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
