name: Test secrets and environments

on:
  workflow_dispatch:
  push:
    branches:
      - '431-reusable-actions'


jobs:
  test-test:
    uses: wultra/wultra-infrastructure/.github/workflows/test-action.yml@develop
    with:
      environment: test
    secrets:
      test: ${{ secrets.TEST_SECRET }}


  test-publish:
    uses: wultra/wultra-infrastructure/.github/workflows/test-action.yml@develop
    with:
      environment: maven-public
    secrets:
      test: ${{ secrets.TEST_SECRET }}